# ==========================================
# DEPLOYMENT DEL FRONTEND
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-despacho
spec:
  replicas: 2 # 2 copias de tu página web para soportar más tráfico
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        # NOTA: Tu imagen con el nginx.conf actualizado
        image: 637423587001.dkr.ecr.us-east-1.amazonaws.com/innovatech-frontend:v1
        resources:
          requests:
            cpu: "100m" # Esto es necesario para el HPA
        ports:
        - containerPort: 80

---
# ==========================================
# SERVICIO: EXPOSICIÓN A INTERNET
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # ¡Esto es clave! Le pide a AWS que cree un ELB (Elastic Load Balancer) público.
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend