# 1. AUTOESCALADOR PARA EL FRONTEND
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-despacho
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---
# 2. AUTOESCALADOR PARA EL BACKEND DE VENTAS
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ventas-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ventas-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---
# 3. AUTOESCALADOR PARA EL BACKEND DE DESPACHOS
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: despachos-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: despachos-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50