name: CI/CD - Backend Ventas

on:
  push:
    branches: [deploy]
    paths:
      - 'back-Ventas_SpringBoot/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y Push Imagen (Etiqueta ventas-v1)
        run: |
          docker build -t ${{ secrets.ECR_REPO_URL_BACKEND }}:ventas-v1 ./back-Ventas_SpringBoot/Springboot-API-REST
          docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:ventas-v1

      - name: Desplegar en EC2 Backend vía SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_BACKEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
              "docker pull ${{ secrets.ECR_REPO_URL_BACKEND }}:ventas-v1",
              "docker stop ventas-api || true",
              "docker rm ventas-api || true",
              "docker run -d --name ventas-api -p 8082:8080 -e SPRING_DATASOURCE_URL=jdbc:mysql://10.0.8.89:3306/innovatech_db -e SPRING_DATASOURCE_USERNAME=admin -e SPRING_DATASOURCE_PASSWORD=admin123 ${{ secrets.ECR_REPO_URL_BACKEND }}:ventas-v1"
            ]}'